CREATE TABLE IF NOT EXISTS schema_migrations (
  version VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  checksum CHAR(64) NOT NULL,
  applied_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crawler_packages (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  package_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  active_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
  protocol_version VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  output_schema_version INT UNSIGNED NULL,
  table_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL UNIQUE,
  manifest_json JSON NOT NULL,
  schema_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  artifact_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  default_config_json JSON NOT NULL,
  secret_refs_json JSON NOT NULL,
  active_artifact_path VARCHAR(1024) NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  install_state_json JSON NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  INDEX idx_packages_status_category (status, category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS monitors (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  query_text VARCHAR(1000) NOT NULL,
  aliases_json JSON NOT NULL,
  selected_categories_json JSON NOT NULL,
  auto_include_new_packages TINYINT(1) NOT NULL DEFAULT 1,
  schedule_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  schedule_time TIME NULL,
  weekday TINYINT UNSIGNED NULL,
  timezone VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Asia/Shanghai',
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  last_run_at DATETIME(6) NULL,
  next_run_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  INDEX idx_monitors_due (enabled, next_run_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS monitor_packages (
  monitor_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  item_limit INT UNSIGNED NOT NULL DEFAULT 100,
  config_json JSON NOT NULL,
  cursor_json JSON NULL,
  cursor_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_success_at DATETIME(6) NULL,
  last_error TEXT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (monitor_id, package_id),
  CONSTRAINT fk_monitor_packages_monitor FOREIGN KEY (monitor_id) REFERENCES monitors(id) ON DELETE RESTRICT,
  CONSTRAINT fk_monitor_packages_package FOREIGN KEY (package_id) REFERENCES crawler_packages(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS monitor_runs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  monitor_id BIGINT UNSIGNED NOT NULL,
  trigger_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  dedupe_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_snapshot_json JSON NOT NULL,
  fetched BIGINT UNSIGNED NOT NULL DEFAULT 0,
  inserted BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated BIGINT UNSIGNED NOT NULL DEFAULT 0,
  unchanged BIGINT UNSIGNED NOT NULL DEFAULT 0,
  rejected BIGINT UNSIGNED NOT NULL DEFAULT 0,
  scheduled_for DATETIME(6) NULL,
  started_at DATETIME(6) NULL,
  finished_at DATETIME(6) NULL,
  cancel_requested_at DATETIME(6) NULL,
  error_message TEXT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_monitor_runs_monitor FOREIGN KEY (monitor_id) REFERENCES monitors(id) ON DELETE RESTRICT,
  INDEX idx_monitor_runs_monitor (monitor_id, created_at),
  INDEX idx_monitor_runs_status (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS package_runs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NOT NULL,
  attempt_no INT UNSIGNED NOT NULL,
  execution_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
  package_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  schema_version INT UNSIGNED NOT NULL,
  artifact_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  artifact_path VARCHAR(1024) NOT NULL,
  request_snapshot_json JSON NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  available_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  worker_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  lease_token CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  lease_expires_at DATETIME(6) NULL,
  heartbeat_at DATETIME(6) NULL,
  exit_code INT NULL,
  fetched BIGINT UNSIGNED NOT NULL DEFAULT 0,
  inserted BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated BIGINT UNSIGNED NOT NULL DEFAULT 0,
  unchanged BIGINT UNSIGNED NOT NULL DEFAULT 0,
  rejected BIGINT UNSIGNED NOT NULL DEFAULT 0,
  batch_duplicates BIGINT UNSIGNED NOT NULL DEFAULT 0,
  result_json JSON NULL,
  work_dir VARCHAR(1024) NULL,
  log_path VARCHAR(1024) NULL,
  error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  error_message TEXT NULL,
  started_at DATETIME(6) NULL,
  finished_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_package_runs_run FOREIGN KEY (run_id) REFERENCES monitor_runs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_package_runs_package FOREIGN KEY (package_id) REFERENCES crawler_packages(id) ON DELETE RESTRICT,
  UNIQUE KEY uk_package_run_attempt (run_id, package_id, attempt_no),
  INDEX idx_package_runs_queue (status, available_at),
  INDEX idx_package_runs_lease (status, lease_expires_at),
  INDEX idx_package_runs_package (package_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS monitor_resource_matches (
  monitor_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NOT NULL,
  resource_uid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  first_run_id BIGINT UNSIGNED NOT NULL,
  last_run_id BIGINT UNSIGNED NOT NULL,
  first_package_run_id BIGINT UNSIGNED NOT NULL,
  last_package_run_id BIGINT UNSIGNED NOT NULL,
  first_matched_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_matched_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  match_count BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (monitor_id, package_id, resource_uid),
  CONSTRAINT fk_matches_monitor_package FOREIGN KEY (monitor_id, package_id) REFERENCES monitor_packages(monitor_id, package_id) ON DELETE RESTRICT,
  CONSTRAINT fk_matches_first_run FOREIGN KEY (first_run_id) REFERENCES monitor_runs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_matches_last_run FOREIGN KEY (last_run_id) REFERENCES monitor_runs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_matches_first_package_run FOREIGN KEY (first_package_run_id) REFERENCES package_runs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_matches_last_package_run FOREIGN KEY (last_package_run_id) REFERENCES package_runs(id) ON DELETE RESTRICT,
  INDEX idx_matches_resource (package_id, resource_uid),
  INDEX idx_matches_monitor_recent (monitor_id, last_matched_at, package_id, resource_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
